type Query {
  hello: String
  products: [Product!]!
  product(id: ID!): Product
}

type Product {
  id: ID!
  price: Float
  name: String
  quantity: Int
  onSale: Boolean
  description: String
  image: String
}
